version: 0.2
phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=787588272122.dkr.ecr.ap-south-1.amazonaws.com/microservicerepo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
   
    post_build:
      commands:
        - echo Build completed on `date`
        - echo Pushing the Docker images...
        - echo Build completed on `date`
        - echo Pushing the Docker image...
        - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
   files:
     - target/Spring-Boot-docker-image.jar
